const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib0RKSXU3TjNFaVVvMHdlWGErcDR5dVdWVzVCbEsrZGtLcjZhdmlmTC8zbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYmVLMTd0NFRQZGRwVkVqRjh3Tms1elg0bE9ZdzdXY3Q4ZVhEYXhqSkRIND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhS2ZlSlN5OXpxUFV0VlZjRzk2bmJNb3d5S0xzUkJNQ2tNdkJNZXBrU21RPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJYem8xUUxCNmVUT1JCYkVKTUV3L3MzNDJraEhTOGdpcTdXZGJ6b1JEWm0wPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNEaXN5cmRxbkwySFp0N3F1aTl5SWZMQ3k3Z05mWkxVKzNpR2RIeXJabGc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVpQjFQYVQ5dWM2VENZTHZiMzZ2VExsbkRNRy8zNnRxUGxoYXd5YUl6a3M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0NsRGlXZnNjQlF2d01UTlcvQWtyVGpicXEyWVk0dUJMWld4Vmp6c3NuND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV2NjYSt1ajFjY3BNdnZQY0h4Z0wxdGZmenQvaDRDOEo2ZFdxdU8wRU5END0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpBeTAvSStybnlLczFNclNGQTVoV1ZzV0k0UUI1ZWwzbUJxb3UwcmlyVTBaQTdoRHRUblREUjNqTkliUFFEcllzd1ZhenhYOEFBQkw4VjdTRHM4UURRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQ0LCJhZHZTZWNyZXRLZXkiOiJUODdwOTFlQ3JhUVFKcm9jS2p1UzNpOFQzczhWMzVzc01JaFNIWGhiQjJVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI5NTZRNTFYUiIsIm1lIjp7ImlkIjoiOTIzMjM1OTYyMjY4OjlAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxOTg0NDA5Nzc5ODU2ODA6OUBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0p6NWovQUJFTi9yNDc4R0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkU1b3hBZDZodGxpWEUySUI4U3VsMDR6dEtndFVPNFgwK0pZK0lIcFZlRkE9IiwiYWNjb3VudFNpZ25hdHVyZSI6Ik5hN09mdS9KYXp3TEtraXpZY1h5SVNTMnAvR3U3L0diVXVsWkRmbTFSSk9wRjQ0OUpDYlhlRzQyYzZxbDhTM1NvZzRJMkRiRjlhVmg1MXFkTXFSd0FnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJWLzRDVzVXaXZSUlR4UjdJTXhzc2k0YUNuOGR5clpSbFdSQlc2ZDBTY1ZTbkZ0T0hLZHNOclc0c2svK2xmTWtYbGMyZFFwRFcvSnVKTHA5SzNZaWNEZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkyMzIzNTk2MjI2ODo5QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlJPYU1RSGVvYlpZbHhOaUFmRXJwZE9NN1NvTFZEdUY5UGlXUGlCNlZYaFEifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNCSUlCUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0NDM2OTEzMywibGFzdFByb3BIYXNoIjoiMUs0aEg0IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFKRFEifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
